// Mocks generated by Mockito 5.4.4 from annotations
// in temperature_studio/test/recording_service_feature_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:isar/isar.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:temperature_studio/src/database/database_service.dart' as _i3;
import 'package:temperature_studio/src/database/models/measurement_models.dart'
    as _i5;
import 'package:temperature_studio/src/hardware/serial_hardware_interface.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIsar_0 extends _i1.SmartFake implements _i2.Isar {
  _FakeIsar_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  @override
  _i2.Isar get isar => (super.noSuchMethod(
        Invocation.getter(#isar),
        returnValue: _FakeIsar_0(
          this,
          Invocation.getter(#isar),
        ),
        returnValueForMissingStub: _FakeIsar_0(
          this,
          Invocation.getter(#isar),
        ),
      ) as _i2.Isar);

  @override
  _i4.Future<int> createSession(_i5.RecordingSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [session],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i5.RecordingSession?> getSession(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getSession,
          [id],
        ),
        returnValue: _i4.Future<_i5.RecordingSession?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.RecordingSession?>.value(),
      ) as _i4.Future<_i5.RecordingSession?>);

  @override
  _i4.Future<List<_i5.RecordingSession>> getAllSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSessions,
          [],
        ),
        returnValue: _i4.Future<List<_i5.RecordingSession>>.value(
            <_i5.RecordingSession>[]),
        returnValueForMissingStub: _i4.Future<List<_i5.RecordingSession>>.value(
            <_i5.RecordingSession>[]),
      ) as _i4.Future<List<_i5.RecordingSession>>);

  @override
  _i4.Future<List<_i5.RecordingSession>> getAllSessionsNewestFirst() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSessionsNewestFirst,
          [],
        ),
        returnValue: _i4.Future<List<_i5.RecordingSession>>.value(
            <_i5.RecordingSession>[]),
        returnValueForMissingStub: _i4.Future<List<_i5.RecordingSession>>.value(
            <_i5.RecordingSession>[]),
      ) as _i4.Future<List<_i5.RecordingSession>>);

  @override
  _i4.Future<void> saveReadings(List<_i5.TemperatureReading>? readings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveReadings,
          [readings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TemperatureReading>> getReadingsForSession(
          int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsForSession,
          [sessionId],
        ),
        returnValue: _i4.Future<List<_i5.TemperatureReading>>.value(
            <_i5.TemperatureReading>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.TemperatureReading>>.value(
                <_i5.TemperatureReading>[]),
      ) as _i4.Future<List<_i5.TemperatureReading>>);

  @override
  _i4.Future<int> countReadingsForSession(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #countReadingsForSession,
          [sessionId],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.TemperatureReading>> getReadingsInRange(
    int? sessionId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsInRange,
          [
            sessionId,
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i5.TemperatureReading>>.value(
            <_i5.TemperatureReading>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.TemperatureReading>>.value(
                <_i5.TemperatureReading>[]),
      ) as _i4.Future<List<_i5.TemperatureReading>>);
}

/// A class which mocks [SerialHardwareInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialHardwareInterface extends _i1.Mock
    implements _i6.SerialHardwareInterface {
  @override
  _i4.Future<List<String>> getDevices() => (super.noSuchMethod(
        Invocation.method(
          #getDevices,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<_i4.Stream<List<int>>> connect(String? devicePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [devicePath],
        ),
        returnValue: _i4.Future<_i4.Stream<List<int>>>.value(
            _i4.Stream<List<int>>.empty()),
        returnValueForMissingStub: _i4.Future<_i4.Stream<List<int>>>.value(
            _i4.Stream<List<int>>.empty()),
      ) as _i4.Future<_i4.Stream<List<int>>>);

  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendData(List<int>? data) => (super.noSuchMethod(
        Invocation.method(
          #sendData,
          [data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
