// Mocks generated by Mockito 5.4.4 from annotations
// in temperature_studio/test/recording_service_feature_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:temperature_studio/src/database/database_service.dart' as _i2;
import 'package:temperature_studio/src/database/models/measurement_models.dart'
    as _i4;
import 'package:temperature_studio/src/hardware/serial_hardware_interface.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i2.Database {
  @override
  _i3.Future<int> createSession(_i4.RecordingSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [session],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i4.RecordingSession?> getSession(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getSession,
          [id],
        ),
        returnValue: _i3.Future<_i4.RecordingSession?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.RecordingSession?>.value(),
      ) as _i3.Future<_i4.RecordingSession?>);

  @override
  _i3.Future<List<_i4.RecordingSession>> getAllSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSessions,
          [],
        ),
        returnValue: _i3.Future<List<_i4.RecordingSession>>.value(
            <_i4.RecordingSession>[]),
        returnValueForMissingStub: _i3.Future<List<_i4.RecordingSession>>.value(
            <_i4.RecordingSession>[]),
      ) as _i3.Future<List<_i4.RecordingSession>>);

  @override
  _i3.Future<List<_i4.RecordingSession>> getAllSessionsNewestFirst() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSessionsNewestFirst,
          [],
        ),
        returnValue: _i3.Future<List<_i4.RecordingSession>>.value(
            <_i4.RecordingSession>[]),
        returnValueForMissingStub: _i3.Future<List<_i4.RecordingSession>>.value(
            <_i4.RecordingSession>[]),
      ) as _i3.Future<List<_i4.RecordingSession>>);

  @override
  _i3.Future<void> saveReadings(List<_i4.TemperatureReading>? readings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveReadings,
          [readings],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.TemperatureReading>> getReadingsForSession(
          int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsForSession,
          [sessionId],
        ),
        returnValue: _i3.Future<List<_i4.TemperatureReading>>.value(
            <_i4.TemperatureReading>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.TemperatureReading>>.value(
                <_i4.TemperatureReading>[]),
      ) as _i3.Future<List<_i4.TemperatureReading>>);

  @override
  _i3.Future<int> countReadingsForSession(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #countReadingsForSession,
          [sessionId],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.TemperatureReading>> getReadingsInRange(
    int? sessionId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsInRange,
          [
            sessionId,
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<List<_i4.TemperatureReading>>.value(
            <_i4.TemperatureReading>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.TemperatureReading>>.value(
                <_i4.TemperatureReading>[]),
      ) as _i3.Future<List<_i4.TemperatureReading>>);

  @override
  _i3.Future<int> saveMarker(_i4.SessionMarker? marker) => (super.noSuchMethod(
        Invocation.method(
          #saveMarker,
          [marker],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.SessionMarker>> getMarkersForSession(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkersForSession,
          [sessionId],
        ),
        returnValue:
            _i3.Future<List<_i4.SessionMarker>>.value(<_i4.SessionMarker>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.SessionMarker>>.value(<_i4.SessionMarker>[]),
      ) as _i3.Future<List<_i4.SessionMarker>>);

  @override
  _i3.Future<int> countMarkersForSession(int? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #countMarkersForSession,
          [sessionId],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [SerialHardwareInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialHardwareInterface extends _i1.Mock
    implements _i5.SerialHardwareInterface {
  @override
  _i3.Future<List<String>> getDevices() => (super.noSuchMethod(
        Invocation.method(
          #getDevices,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<_i3.Stream<List<int>>> connect(String? devicePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [devicePath],
        ),
        returnValue: _i3.Future<_i3.Stream<List<int>>>.value(
            _i3.Stream<List<int>>.empty()),
        returnValueForMissingStub: _i3.Future<_i3.Stream<List<int>>>.value(
            _i3.Stream<List<int>>.empty()),
      ) as _i3.Future<_i3.Stream<List<int>>>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendData(List<int>? data) => (super.noSuchMethod(
        Invocation.method(
          #sendData,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
